/**
 * Cron preset helpers for the scheduled-task form.
 *
 * Pure functions, no external deps. Cron expressions produced by presets are
 * generated by us, so we never need to parse arbitrary cron for the happy path;
 * `parseCron` only round-trips the canonical shapes we emit and falls back to
 * `custom` for anything else.
 */

export type CronPreset = "hourly" | "daily" | "weekly" | "monthly" | "custom";

export type Weekday = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type CronParts = {
  minute?: number;
  hour?: number;
  weekdays?: Weekday[];
  dayOfMonth?: number;
  raw?: string;
};

export type ScheduleFormState = {
  scheduleType: "once" | "cron";
  preset?: CronPreset;
  parts?: CronParts;
  /** datetime-local wall value "YYYY-MM-DDTHH:mm", interpreted in `timezone`. */
  runAtLocal?: string;
  timezone: string;
};

export type ScheduleLocale = "en" | "zh";

export const WEEKDAYS: Weekday[] = [
  "mon",
  "tue",
  "wed",
  "thu",
  "fri",
  "sat",
  "sun",
];

const WEEKDAY_TO_CRON: Record<Weekday, string> = {
  mon: "1",
  tue: "2",
  wed: "3",
  thu: "4",
  fri: "5",
  sat: "6",
  sun: "0",
};

const CRON_TO_WEEKDAY: Record<string, Weekday> = {
  "0": "sun",
  "1": "mon",
  "2": "tue",
  "3": "wed",
  "4": "thu",
  "5": "fri",
  "6": "sat",
  "7": "sun",
};

const EN_WEEKDAY: Record<Weekday, string> = {
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  sat: "Sat",
  sun: "Sun",
};

const ZH_WEEKDAY: Record<Weekday, string> = {
  mon: "周一",
  tue: "周二",
  wed: "周三",
  thu: "周四",
  fri: "周五",
  sat: "周六",
  sun: "周日",
};

function clamp(
  value: number | undefined,
  min: number,
  max: number,
  fallback: number,
): number {
  const n =
    typeof value === "number" && Number.isFinite(value) ? value : fallback;
  return Math.max(min, Math.min(max, Math.trunc(n)));
}

export function pad2(n: number): string {
  return String(Math.trunc(Number.isFinite(n) ? n : 0)).padStart(2, "0");
}

function orderedWeekdays(days: Weekday[] | undefined): Weekday[] {
  const set = new Set(days ?? []);
  return WEEKDAYS.filter((w) => set.has(w));
}

export function serializeCron(preset: CronPreset, parts: CronParts): string {
  const m = clamp(parts.minute, 0, 59, 0);
  const h = clamp(parts.hour, 0, 23, 9);
  switch (preset) {
    case "hourly":
      return `${m} * * * *`;
    case "daily":
      return `${m} ${h} * * *`;
    case "weekly": {
      const ordered = orderedWeekdays(parts.weekdays);
      if (ordered.length === 0) {
        return `${m} ${h} * * *`;
      }
      const dow = ordered.map((w) => WEEKDAY_TO_CRON[w]).join(",");
      return `${m} ${h} * * ${dow}`;
    }
    case "monthly": {
      const dom = clamp(parts.dayOfMonth, 1, 31, 1);
      return `${m} ${h} ${dom} * *`;
    }
    case "custom":
      return (parts.raw ?? "").trim() || "0 9 * * *";
  }
  // Unreachable — the switch above is exhaustive over CronPreset.
  return (parts.raw ?? "").trim() || "0 9 * * *";
}

function isStar(field: string): boolean {
  return field === "*";
}

function isSimpleDowList(field: string): boolean {
  return field.split(",").every((tok) => /^[0-7]$/.test(tok));
}

export function parseCron(cron: string): {
  preset: CronPreset;
  parts: CronParts;
} {
  const expr = cron.trim();
  const fields = expr.split(/\s+/);
  if (fields.length !== 5) {
    return { preset: "custom", parts: { raw: expr } };
  }
  // fields.length === 5 is verified above, so every index is defined.
  const mF = fields[0]!;
  const hF = fields[1]!;
  const domF = fields[2]!;
  const monF = fields[3]!;
  const dowF = fields[4]!;
  const numMinute = /^\d+$/.test(mF);
  const numHour = /^\d+$/.test(hF);
  const numDom = /^\d+$/.test(domF);
  const stars = isStar(domF) && isStar(monF);

  // hourly: "M * * * *"
  if (numMinute && isStar(hF) && stars && isStar(dowF)) {
    return { preset: "hourly", parts: { minute: Number(mF) } };
  }
  // daily: "M H * * *"
  if (numMinute && numHour && stars && isStar(dowF)) {
    return {
      preset: "daily",
      parts: { minute: Number(mF), hour: Number(hF) },
    };
  }
  // weekly: "M H * * DOW" (simple comma list of single digits only)
  if (
    numMinute &&
    numHour &&
    isStar(domF) &&
    isStar(monF) &&
    !isStar(dowF) &&
    isSimpleDowList(dowF)
  ) {
    const parsed = dowF
      .split(",")
      .map((tok) => CRON_TO_WEEKDAY[tok])
      .filter((w): w is Weekday => Boolean(w));
    const ordered = orderedWeekdays(parsed);
    if (ordered.length > 0) {
      return {
        preset: "weekly",
        parts: { minute: Number(mF), hour: Number(hF), weekdays: ordered },
      };
    }
  }
  // monthly: "M H DOM * *"
  if (numMinute && numHour && numDom && isStar(monF) && isStar(dowF)) {
    return {
      preset: "monthly",
      parts: { minute: Number(mF), hour: Number(hF), dayOfMonth: Number(domF) },
    };
  }
  return { preset: "custom", parts: { raw: expr } };
}

export function describeSchedule(
  state: ScheduleFormState,
  locale: ScheduleLocale,
): string {
  const tz = state.timezone;
  const zh = locale === "zh";

  if (state.scheduleType === "once") {
    const runAt = (state.runAtLocal ?? "").replace("T", " ");
    return zh ? `单次 ${runAt} (${tz})` : `Once at ${runAt} (${tz})`;
  }

  const parts = state.parts ?? {};
  const hhmm = `${pad2(parts.hour ?? 0)}:${pad2(parts.minute ?? 0)}`;

  switch (state.preset) {
    case "hourly": {
      const minute = parts.minute ?? 0;
      return zh
        ? `每小时第 ${minute} 分钟 (${tz})`
        : `Every hour at :${pad2(minute)} (${tz})`;
    }
    case "daily":
      return zh ? `每天 ${hhmm} (${tz})` : `Every day at ${hhmm} (${tz})`;
    case "weekly": {
      const ordered = orderedWeekdays(parts.weekdays);
      if (ordered.length === 0) {
        return zh ? `每天 ${hhmm} (${tz})` : `Every day at ${hhmm} (${tz})`;
      }
      if (zh) {
        const names = ordered.map((w) => ZH_WEEKDAY[w]).join("、");
        return `每周 ${names} ${hhmm} (${tz})`;
      }
      const names = ordered.map((w) => EN_WEEKDAY[w]).join(", ");
      return `Every ${names} at ${hhmm} (${tz})`;
    }
    case "monthly": {
      const dom = parts.dayOfMonth ?? 1;
      return zh
        ? `每月 ${dom} 日 ${hhmm} (${tz})`
        : `On day ${dom} of every month at ${hhmm} (${tz})`;
    }
    case "custom":
      return zh
        ? `自定义: ${parts.raw ?? ""} (${tz})`
        : `Custom: ${parts.raw ?? ""} (${tz})`;
  }
  // Unreachable — switch is exhaustive over CronPreset.
  return zh ? `自定义 (${tz})` : `Custom (${tz})`;
}

/**
 * Convert a datetime-local wall value (interpreted in `timezone`) to a UTC ISO
 * string. The backend's `datetime.fromisoformat` treats naive strings as UTC,
 * so we must submit an explicit offset. DST-safe via Intl.
 */
export function zonedLocalToUtcIso(
  localValue: string,
  timezone: string,
): string {
  const [date, time] = localValue.split("T");
  const [y, mo, d] = (date ?? "").split("-").map(Number);
  const [h, mi] = (time ?? "00:00").split(":").map(Number);
  const refMs = Date.UTC(y ?? 1970, (mo ?? 1) - 1, d ?? 1, h ?? 0, mi ?? 0);
  // The offset at the wall-time-as-UTC instant is stale when a DST transition
  // sits between that instant and the real one (e.g. "03:30" the morning of
  // spring-forward resolves with the pre-transition offset, firing an hour
  // late and breaking the round-trip with `utcToZonedLocalInput`). Resolve
  // once, then re-derive the offset at the candidate instant; one correction
  // converges for real timezones.
  let offsetMs = tzOffsetMs(timezone, new Date(refMs));
  let utcMs = refMs - offsetMs;
  const correctedOffsetMs = tzOffsetMs(timezone, new Date(utcMs));
  if (correctedOffsetMs !== offsetMs) {
    offsetMs = correctedOffsetMs;
    utcMs = refMs - offsetMs;
  }
  const utc = new Date(utcMs);
  return `${utc.getUTCFullYear()}-${pad2(utc.getUTCMonth() + 1)}-${pad2(
    utc.getUTCDate(),
  )}T${pad2(utc.getUTCHours())}:${pad2(utc.getUTCMinutes())}:${pad2(
    utc.getUTCSeconds(),
  )}+00:00`;
}

/**
 * Inverse of `zonedLocalToUtcIso`: render a stored UTC ISO as the datetime-local
 * wall value ("YYYY-MM-DDTHH:mm") in `timezone`. Used when editing a one-time task.
 */
export function utcToZonedLocalInput(iso: string, timezone: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) {
    return "";
  }
  const offsetMs = tzOffsetMs(timezone, d);
  const local = new Date(d.getTime() + offsetMs);
  return `${local.getUTCFullYear()}-${pad2(local.getUTCMonth() + 1)}-${pad2(
    local.getUTCDate(),
  )}T${pad2(local.getUTCHours())}:${pad2(local.getUTCMinutes())}`;
}

function tzOffsetMs(timezone: string, date: Date): number {
  const tzParts = formatParts(timezone, date);
  const utcParts = formatParts("UTC", date);
  const tzMs = toUtcMs(tzParts);
  const utcMs = toUtcMs(utcParts);
  // >0 means the timezone wall clock is ahead of UTC (east of UTC).
  return tzMs - utcMs;
}

function formatParts(timezone: string, date: Date): Record<string, number> {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    hourCycle: "h23",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  }).formatToParts(date);
  const out: Record<string, number> = {};
  for (const p of parts) {
    out[p.type] = Number(p.value);
  }
  return out;
}

function toUtcMs(p: Record<string, number>): number {
  return Date.UTC(
    p.year ?? 1970,
    (p.month ?? 1) - 1,
    p.day ?? 1,
    p.hour ?? 0,
    p.minute ?? 0,
    p.second ?? 0,
  );
}
